name: Deploy Multiple Resources

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare deploy folder
      run: |
        mkdir deploy
        cp -r note deploy/
        cp -r images deploy/
        cp -r materials deploy/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HOMEPAGE_TOKEN }}
        publish_dir: ./deploy
        publish_branch: gh-pages
        force_orphan: true